### ISSUE TITLE
Can this still compile ?

### ISSUE THREAD

**Issue by elig0n** [KubaO/podofobrowser#1]
What would be the values for the linux CMake command, i.e.

    cmake -G "Unix Makefiles" \
            -DLIBPODOFO_DIR=/path/to/podofo_install_dir \
            -DCMAKE_INCLUDE_PATH=/path/to/extra/includes \
            -DCMAKE_LIBRARY_PATH=/path/to/extra/libraries

I would figure that LIBPODOFO would be /usr/include/podofo/

**Comment by KubaO** [comment]
“Linux” is way too general to know. What’s your source of libpodofo? I.e. where does it
come from? If it’s installed by your distribution’s package manager, then use that to
investigate where it got installed (e.g. rpm -ql libpodofo) and what’s there.
If you have built it yourself, then the arguments passed to the configure command will
determine where it got installed (if you installed it, that is if you had done `make install`).

Cheers, Kuba

**Comment by ringo458** [comment]
Hi, I built the current version of podofo on centos 7 with qt4 but the 0.5 version of podofobrowser would not make. So I got yours and used the same cmake formula I had pieced together for podofo:

cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$HOME/podofo" -DWANT_LIB64:BOOL=TRUE  -DLIBFREETYPE_FT2BUILD_H=/usr/include/freetype2 -DLIBFREETYPE_FTHEADER_H=/usr/include/freetype2/freetype/config

that seemed to go OK but make died:

[steve@icaress podofobrowser-trunk]$ make
[  4%] Building CXX object src/CMakeFiles/podofobrowser.dir/podofoutil.o
/home/steve/podofo/podofobrowser-trunk/src/podofoutil.cpp:5:21: fatal error: QtWidgets: No such file or directory
 #include <QtWidgets>

I set the QTDIR to qt5 and that didn't fix anything. I've already noticed problems with a few
of the binaries that I built under qt4 so I feel that it;s a good idea to track down something
more modern and maybe build from what you are working with, but that seems to require
SVN and I am an SVN virgin. Given that I am kinda stuck building things my way do you 
know where I can find a version that will work well with your version of the browser.
And do you thing that version is less buggy than the code I found on sourceforge and would
therefore justify building qt5?   Thanks :)

**Comment by KubaO** [comment]
Sorry, I haven’t looked into this in ages. I’ll check into it this week. A Qt source build should be simple, or just use your distributors package. Or macports on Mac.

**Comment by MarjaE2** [comment]
It doesn't currently show up in ports search podofo

**Comment by KubaO** [comment]
Consider it true abandonware at this point. I won’t be touching this in any near future. Sorry

**Comment by drizt** [comment]
Actually CMakeLists.txt is not ported to Qt5. This is the problem. qmake building also not works on Linux but by another reasons.
